"""add siri ride duration minutes

Revision ID: 20227f4d325d
Revises: 45431f3451a3
Create Date: 2021-11-23 20:01:01.320213+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20227f4d325d'
down_revision = '45431f3451a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_ride', sa.Column('updated_first_last_vehicle_locations', sa.DateTime(timezone=True), nullable=True))
    op.add_column('siri_ride', sa.Column('first_vehicle_location_id', sa.Integer(), nullable=True))
    op.add_column('siri_ride', sa.Column('last_vehicle_location_id', sa.Integer(), nullable=True))
    op.add_column('siri_ride', sa.Column('updated_duration_minutes', sa.DateTime(timezone=True), nullable=True))
    op.add_column('siri_ride', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_siri_ride_duration_minutes'), 'siri_ride', ['duration_minutes'], unique=False)
    op.create_index(op.f('ix_siri_ride_updated_duration_minutes'), 'siri_ride', ['updated_duration_minutes'], unique=False)
    op.create_index(op.f('ix_siri_ride_updated_first_last_vehicle_locations'), 'siri_ride', ['updated_first_last_vehicle_locations'], unique=False)
    op.create_foreign_key(op.f('fk_siri_ride_last_vehicle_location_id_siri_vehicle_location'), 'siri_ride', 'siri_vehicle_location', ['last_vehicle_location_id'], ['id'])
    op.create_foreign_key(op.f('fk_siri_ride_first_vehicle_location_id_siri_vehicle_location'), 'siri_ride', 'siri_vehicle_location', ['first_vehicle_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_siri_ride_first_vehicle_location_id_siri_vehicle_location'), 'siri_ride', type_='foreignkey')
    op.drop_constraint(op.f('fk_siri_ride_last_vehicle_location_id_siri_vehicle_location'), 'siri_ride', type_='foreignkey')
    op.drop_index(op.f('ix_siri_ride_updated_first_last_vehicle_locations'), table_name='siri_ride')
    op.drop_index(op.f('ix_siri_ride_updated_duration_minutes'), table_name='siri_ride')
    op.drop_index(op.f('ix_siri_ride_duration_minutes'), table_name='siri_ride')
    op.drop_column('siri_ride', 'duration_minutes')
    op.drop_column('siri_ride', 'updated_duration_minutes')
    op.drop_column('siri_ride', 'last_vehicle_location_id')
    op.drop_column('siri_ride', 'first_vehicle_location_id')
    op.drop_column('siri_ride', 'updated_first_last_vehicle_locations')
    # ### end Alembic commands ###
