"""empty message

Revision ID: 20f920736aab
Revises: 
Create Date: 2021-05-05 04:52:27.277079+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f920736aab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_date', sa.Date(), nullable=True),
    sa.Column('max_date', sa.Date(), nullable=True),
    sa.Column('line_ref', sa.Integer(), nullable=True),
    sa.Column('operator_ref', sa.Integer(), nullable=True),
    sa.Column('siri_published_line_name', sa.String(), nullable=True),
    sa.Column('gtfs_route_short_name', sa.String(), nullable=True),
    sa.Column('gtfs_route_long_name', sa.String(), nullable=True),
    sa.Column('gtfs_route_mkt', sa.String(), nullable=True),
    sa.Column('gtfs_route_direction', sa.String(), nullable=True),
    sa.Column('gtfs_route_alternative', sa.String(), nullable=True),
    sa.Column('gtfs_agency_name', sa.String(), nullable=True),
    sa.Column('gtfs_route_type', sa.String(), nullable=True),
    sa.Column('is_from_gtfs', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
