"""add siri-dedicated tables

Revision ID: 366df3cd0db1
Revises: 396e189450e9
Create Date: 2021-11-07 09:48:26.525585+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '366df3cd0db1'
down_revision = '396e189450e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siri_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_ref', sa.Integer(), nullable=True),
    sa.Column('operator_ref', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siri_route_line_ref'), 'siri_route', ['line_ref'], unique=False)
    op.create_index(op.f('ix_siri_route_operator_ref'), 'siri_route', ['operator_ref'], unique=False)
    op.create_table('siri_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siri_stop_code'), 'siri_stop', ['code'], unique=False)
    op.create_table('siri_ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siri_route_id', sa.Integer(), nullable=True),
    sa.Column('journey_ref', sa.String(), nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(), nullable=True),
    sa.Column('vehicle_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['siri_route_id'], ['siri_route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siri_ride_journey_ref'), 'siri_ride', ['journey_ref'], unique=False)
    op.create_index(op.f('ix_siri_ride_scheduled_start_time'), 'siri_ride', ['scheduled_start_time'], unique=False)
    op.create_index(op.f('ix_siri_ride_siri_route_id'), 'siri_ride', ['siri_route_id'], unique=False)
    op.create_index(op.f('ix_siri_ride_vehicle_ref'), 'siri_ride', ['vehicle_ref'], unique=False)
    op.create_table('siri_ride_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siri_stop_id', sa.Integer(), nullable=True),
    sa.Column('siri_ride_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['siri_ride_id'], ['siri_ride.id'], ),
    sa.ForeignKeyConstraint(['siri_stop_id'], ['siri_stop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_siri_ride_stop_order'), 'siri_ride_stop', ['order'], unique=False)
    op.create_index(op.f('ix_siri_ride_stop_siri_ride_id'), 'siri_ride_stop', ['siri_ride_id'], unique=False)
    op.create_index(op.f('ix_siri_ride_stop_siri_stop_id'), 'siri_ride_stop', ['siri_stop_id'], unique=False)
    op.create_table('siri_vehicle_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siri_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('siri_ride_stop_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at_time', sa.DateTime(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('distance_from_journey_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['siri_ride_stop_id'], ['siri_ride_stop.id'], ),
    sa.ForeignKeyConstraint(['siri_snapshot_id'], ['siri_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicle_location')
    op.add_column('siri_snapshot', sa.Column('num_added_siri_rides', sa.Integer(), nullable=True))
    op.add_column('siri_snapshot', sa.Column('num_added_siri_ride_stops', sa.Integer(), nullable=True))
    op.add_column('siri_snapshot', sa.Column('num_added_siri_routes', sa.Integer(), nullable=True))
    op.add_column('siri_snapshot', sa.Column('num_added_siri_stops', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_snapshot', 'num_added_siri_stops')
    op.drop_column('siri_snapshot', 'num_added_siri_routes')
    op.drop_column('siri_snapshot', 'num_added_siri_ride_stops')
    op.drop_column('siri_snapshot', 'num_added_siri_rides')
    op.create_table('vehicle_location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('siri_snapshot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ride_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('route_stop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recorded_at_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bearing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('velocity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_from_journey_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name='vehicle_location_ride_id_fkey'),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stop.id'], name='vehicle_location_route_stop_id_fkey'),
    sa.ForeignKeyConstraint(['siri_snapshot_id'], ['siri_snapshot.id'], name='vehicle_location_siri_snapshot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicle_location_pkey')
    )
    op.drop_table('siri_vehicle_location')
    op.drop_index(op.f('ix_siri_ride_stop_siri_stop_id'), table_name='siri_ride_stop')
    op.drop_index(op.f('ix_siri_ride_stop_siri_ride_id'), table_name='siri_ride_stop')
    op.drop_index(op.f('ix_siri_ride_stop_order'), table_name='siri_ride_stop')
    op.drop_table('siri_ride_stop')
    op.drop_index(op.f('ix_siri_ride_vehicle_ref'), table_name='siri_ride')
    op.drop_index(op.f('ix_siri_ride_siri_route_id'), table_name='siri_ride')
    op.drop_index(op.f('ix_siri_ride_scheduled_start_time'), table_name='siri_ride')
    op.drop_index(op.f('ix_siri_ride_journey_ref'), table_name='siri_ride')
    op.drop_table('siri_ride')
    op.drop_index(op.f('ix_siri_stop_code'), table_name='siri_stop')
    op.drop_table('siri_stop')
    op.drop_index(op.f('ix_siri_route_operator_ref'), table_name='siri_route')
    op.drop_index(op.f('ix_siri_route_line_ref'), table_name='siri_route')
    op.drop_table('siri_route')
    # ### end Alembic commands ###
