"""add num_successful_parse_vehicle_locations to siri_snapshot table

Revision ID: 373777860794
Revises: 4ef223246977
Create Date: 2021-05-06 12:26:10.644007+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373777860794'
down_revision = '4ef223246977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_snapshot', sa.Column('num_successful_parse_vehicle_locations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_snapshot', 'num_successful_parse_vehicle_locations')
    # ### end Alembic commands ###
