"""fix-ride-stop-gtfs-datetime-fields

Revision ID: 396e189450e9
Revises: 9a8f099a15a1
Create Date: 2021-11-02 10:27:09.310684+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '396e189450e9'
down_revision = '9a8f099a15a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_stop', sa.Column('gtfs_arrival_time', sa.String(), nullable=True))
    op.add_column('ride_stop', sa.Column('gtfs_departure_time', sa.String(), nullable=True))
    op.drop_column('ride_stop', 'gtfs_arrival_datetime')
    op.drop_column('ride_stop', 'gtfs_departure_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_stop', sa.Column('gtfs_departure_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ride_stop', sa.Column('gtfs_arrival_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ride_stop', 'gtfs_departure_time')
    op.drop_column('ride_stop', 'gtfs_arrival_time')
    # ### end Alembic commands ###
