"""drop gtfs_ride_stop time fields to change their type

Revision ID: 3d9538d6a33d
Revises: 98562fd77434
Create Date: 2022-01-17 08:16:58.649612+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '3d9538d6a33d'
down_revision = '98562fd77434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gtfs_ride_stop', 'departure_time')
    op.drop_column('gtfs_ride_stop', 'arrival_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_ride_stop', sa.Column('arrival_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gtfs_ride_stop', sa.Column('departure_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
