"""add siri_snapshot.created_by field

Revision ID: 45431f3451a3
Revises: 30d62e479f50
Create Date: 2021-11-14 10:15:27.474321+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45431f3451a3'
down_revision = '30d62e479f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_snapshot', sa.Column('created_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_snapshot', 'created_by')
    # ### end Alembic commands ###
