"""add-index-for-siri-ride-stop-nearest-vehicle-location-id

Revision ID: 4cdcf21fa073
Revises: cb63a0bc2879
Create Date: 2022-04-04 12:14:50.864955+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '4cdcf21fa073'
down_revision = 'cb63a0bc2879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_siri_ride_stop_nearest_siri_vehicle_location_id'), 'siri_ride_stop', ['nearest_siri_vehicle_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siri_ride_stop_nearest_siri_vehicle_location_id'), table_name='siri_ride_stop')
    # ### end Alembic commands ###
