"""add num_failed_parse_vehicle_locations to siri_snapshot

Revision ID: 4ef223246977
Revises: 4767d09f46df
Create Date: 2021-05-06 07:13:14.905468+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef223246977'
down_revision = '4767d09f46df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_snapshot', sa.Column('num_failed_parse_vehicle_locations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_snapshot', 'num_failed_parse_vehicle_locations')
    # ### end Alembic commands ###
