"""add siri_ride_stop.gtfs_stop_id

Revision ID: 57ce9e6f947d
Revises: da5d8fa25139
Create Date: 2022-01-25 10:14:29.266489+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '57ce9e6f947d'
down_revision = 'da5d8fa25139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_ride_stop', sa.Column('gtfs_stop_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_ride_stop', 'gtfs_stop_id')
    # ### end Alembic commands ###
