"""add unique constraints and indices

Revision ID: 67c47a7c2029
Revises: 366df3cd0db1
Create Date: 2021-11-07 17:14:06.435914+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c47a7c2029'
down_revision = '366df3cd0db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_route_journey_ref_vehicle_ref', 'siri_ride', ['siri_route_id', 'journey_ref', 'vehicle_ref'], unique=True)
    op.create_index('idx_ride_stop_order', 'siri_ride_stop', ['siri_ride_id', 'siri_stop_id', 'order'], unique=True)
    op.create_index('idx_operator_ref_line_ref', 'siri_route', ['operator_ref', 'line_ref'], unique=True)
    op.drop_index('ix_siri_snapshot_snapshot_id', table_name='siri_snapshot')
    op.create_index(op.f('ix_siri_snapshot_snapshot_id'), 'siri_snapshot', ['snapshot_id'], unique=True)
    op.drop_index('ix_siri_stop_code', table_name='siri_stop')
    op.create_index(op.f('ix_siri_stop_code'), 'siri_stop', ['code'], unique=True)
    op.create_index(op.f('ix_siri_vehicle_location_recorded_at_time'), 'siri_vehicle_location', ['recorded_at_time'], unique=False)
    op.create_index(op.f('ix_siri_vehicle_location_siri_ride_stop_id'), 'siri_vehicle_location', ['siri_ride_stop_id'], unique=False)
    op.create_index(op.f('ix_siri_vehicle_location_siri_snapshot_id'), 'siri_vehicle_location', ['siri_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siri_vehicle_location_siri_snapshot_id'), table_name='siri_vehicle_location')
    op.drop_index(op.f('ix_siri_vehicle_location_siri_ride_stop_id'), table_name='siri_vehicle_location')
    op.drop_index(op.f('ix_siri_vehicle_location_recorded_at_time'), table_name='siri_vehicle_location')
    op.drop_index(op.f('ix_siri_stop_code'), table_name='siri_stop')
    op.create_index('ix_siri_stop_code', 'siri_stop', ['code'], unique=False)
    op.drop_index(op.f('ix_siri_snapshot_snapshot_id'), table_name='siri_snapshot')
    op.create_index('ix_siri_snapshot_snapshot_id', 'siri_snapshot', ['snapshot_id'], unique=False)
    op.drop_index('idx_operator_ref_line_ref', table_name='siri_route')
    op.drop_index('idx_ride_stop_order', table_name='siri_ride_stop')
    op.drop_index('idx_route_journey_ref_vehicle_ref', table_name='siri_ride')
    # ### end Alembic commands ###
