"""add foreign keys

Revision ID: 6c02b4e9bdad
Revises: 7cc970f13408
Create Date: 2022-03-13 13:10:01.253638+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '6c02b4e9bdad'
down_revision = '7cc970f13408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_gtfs_ride_last_gtfs_ride_stop_id_gtfs_ride_stop'), 'gtfs_ride', 'gtfs_ride_stop', ['last_gtfs_ride_stop_id'], ['id'])
    op.create_foreign_key(op.f('fk_gtfs_ride_first_gtfs_ride_stop_id_gtfs_ride_stop'), 'gtfs_ride', 'gtfs_ride_stop', ['first_gtfs_ride_stop_id'], ['id'])
    op.create_foreign_key(op.f('fk_siri_ride_route_gtfs_ride_id_gtfs_ride'), 'siri_ride', 'gtfs_ride', ['route_gtfs_ride_id'], ['id'])
    op.create_foreign_key(op.f('fk_siri_ride_journey_gtfs_ride_id_gtfs_ride'), 'siri_ride', 'gtfs_ride', ['journey_gtfs_ride_id'], ['id'])
    op.create_foreign_key(op.f('fk_siri_ride_gtfs_ride_id_gtfs_ride'), 'siri_ride', 'gtfs_ride', ['gtfs_ride_id'], ['id'])
    op.create_foreign_key(op.f('fk_siri_ride_stop_gtfs_stop_id_gtfs_stop'), 'siri_ride_stop', 'gtfs_stop', ['gtfs_stop_id'], ['id'])
    op.create_foreign_key(op.f('fk_siri_ride_stop_nearest_siri_vehicle_location_id_siri_vehicle_location'), 'siri_ride_stop', 'siri_vehicle_location', ['nearest_siri_vehicle_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_siri_ride_stop_nearest_siri_vehicle_location_id_siri_vehicle_location'), 'siri_ride_stop', type_='foreignkey')
    op.drop_constraint(op.f('fk_siri_ride_stop_gtfs_stop_id_gtfs_stop'), 'siri_ride_stop', type_='foreignkey')
    op.drop_constraint(op.f('fk_siri_ride_gtfs_ride_id_gtfs_ride'), 'siri_ride', type_='foreignkey')
    op.drop_constraint(op.f('fk_siri_ride_journey_gtfs_ride_id_gtfs_ride'), 'siri_ride', type_='foreignkey')
    op.drop_constraint(op.f('fk_siri_ride_route_gtfs_ride_id_gtfs_ride'), 'siri_ride', type_='foreignkey')
    op.drop_constraint(op.f('fk_gtfs_ride_first_gtfs_ride_stop_id_gtfs_ride_stop'), 'gtfs_ride', type_='foreignkey')
    op.drop_constraint(op.f('fk_gtfs_ride_last_gtfs_ride_stop_id_gtfs_ride_stop'), 'gtfs_ride', type_='foreignkey')
    # ### end Alembic commands ###
