"""add mot_id to gtfs_stop

Revision ID: 7061c817ee1c
Revises: c2828612a8ae
Create Date: 2022-01-16 12:18:08.456686+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '7061c817ee1c'
down_revision = 'c2828612a8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_stop', sa.Column('mot_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_gtfs_stop_mot_id'), 'gtfs_stop', ['mot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gtfs_stop_mot_id'), table_name='gtfs_stop')
    op.drop_column('gtfs_stop', 'mot_id')
    # ### end Alembic commands ###
