"""add index on siri_ride_stop.gtfs_stop_id

Revision ID: 7f5f797b8553
Revises: 71a60506ad90
Create Date: 2022-12-12 17:53:12.115089+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '7f5f797b8553'
down_revision = '71a60506ad90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_siri_ride_stop_gtfs_stop_id'), 'siri_ride_stop', ['gtfs_stop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siri_ride_stop_gtfs_stop_id'), table_name='siri_ride_stop')
    # ### end Alembic commands ###
