"""add siri ride gtfs relations

Revision ID: 7cc970f13408
Revises: baadbcbcd3de
Create Date: 2022-02-01 14:17:00.290873+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '8cc970f13408'
down_revision = '167517cbecae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_ride', sa.Column('scheduled_time_gtfs_ride_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_siri_ride_scheduled_time_gtfs_ride_id_gtfs_ride'), 'siri_ride', 'gtfs_ride',
                          ['scheduled_time_gtfs_ride_id'], ['id'])
    op.create_index(op.f('ix_siri_ride_scheduled_time_gtfs_ride_id'), 'siri_ride', ['scheduled_time_gtfs_ride_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siri_ride_scheduled_time_gtfs_ride_id'), table_name='siri_ride')
    op.drop_constraint(op.f('fk_siri_ride_scheduled_time_gtfs_ride_id_gtfs_ride'), 'siri_ride', type_='foreignkey')
    op.drop_column('siri_ride', 'scheduled_time_gtfs_ride_id')
    # ### end Alembic commands ###
