"""add siri_snapshot table

Revision ID: 8e3e34ffec7c
Revises: 78d860ffa426
Create Date: 2021-05-05 18:06:07.218139+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3e34ffec7c'
down_revision = '78d860ffa426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siri_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('etl_status', sa.Enum('loading', 'loaded', 'error', 'deleted', name='etlstatusenum'), nullable=True),
    sa.Column('etl_start_time', sa.DateTime(), nullable=True),
    sa.Column('etl_end_time', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siri_snapshot')
    # ### end Alembic commands ###
