"""change mot_id to related table gtfs_stop_mot_id

Revision ID: 98562fd77434
Revises: 7061c817ee1c
Create Date: 2022-01-16 17:20:38.475837+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '98562fd77434'
down_revision = '7061c817ee1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtfs_stop_mot_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtfs_stop_id', sa.Integer(), nullable=True),
    sa.Column('mot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gtfs_stop_id'], ['gtfs_stop.id'], name=op.f('fk_gtfs_stop_mot_id_gtfs_stop_id_gtfs_stop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gtfs_stop_mot_id'))
    )
    op.create_index(op.f('ix_gtfs_stop_mot_id_gtfs_stop_id'), 'gtfs_stop_mot_id', ['gtfs_stop_id'], unique=False)
    op.create_index(op.f('ix_gtfs_stop_mot_id_mot_id'), 'gtfs_stop_mot_id', ['mot_id'], unique=False)
    op.drop_index('ix_gtfs_stop_mot_id', table_name='gtfs_stop')
    op.drop_column('gtfs_stop', 'mot_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_stop', sa.Column('mot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_gtfs_stop_mot_id', 'gtfs_stop', ['mot_id'], unique=False)
    op.drop_index(op.f('ix_gtfs_stop_mot_id_mot_id'), table_name='gtfs_stop_mot_id')
    op.drop_index(op.f('ix_gtfs_stop_mot_id_gtfs_stop_id'), table_name='gtfs_stop_mot_id')
    op.drop_table('gtfs_stop_mot_id')
    # ### end Alembic commands ###
