"""add gtfs_ride_stop time field as datetime

Revision ID: 9cc60dd15071
Revises: 3d9538d6a33d
Create Date: 2022-01-17 08:18:03.937110+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = '9cc60dd15071'
down_revision = '3d9538d6a33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_ride_stop', sa.Column('arrival_time', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True))
    op.add_column('gtfs_ride_stop', sa.Column('departure_time', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gtfs_ride_stop', 'departure_time')
    op.drop_column('gtfs_ride_stop', 'arrival_time')
    # ### end Alembic commands ###
