"""add indices for siri etl

Revision ID: 9d73ef9c7fcc
Revises: 373777860794
Create Date: 2021-08-01 14:33:13.303682+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d73ef9c7fcc'
down_revision = '373777860794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ride_is_from_gtfs'), 'ride', ['is_from_gtfs'], unique=False)
    op.create_index(op.f('ix_ride_journey_ref'), 'ride', ['journey_ref'], unique=False)
    op.create_index(op.f('ix_ride_route_id'), 'ride', ['route_id'], unique=False)
    op.create_index(op.f('ix_ride_scheduled_start_time'), 'ride', ['scheduled_start_time'], unique=False)
    op.create_index(op.f('ix_ride_vehicle_ref'), 'ride', ['vehicle_ref'], unique=False)
    op.create_index(op.f('ix_route_is_from_gtfs'), 'route', ['is_from_gtfs'], unique=False)
    op.create_index(op.f('ix_route_line_ref'), 'route', ['line_ref'], unique=False)
    op.create_index(op.f('ix_route_max_date'), 'route', ['max_date'], unique=False)
    op.create_index(op.f('ix_route_min_date'), 'route', ['min_date'], unique=False)
    op.create_index(op.f('ix_route_operator_ref'), 'route', ['operator_ref'], unique=False)
    op.create_index(op.f('ix_route_stop_is_from_gtfs'), 'route_stop', ['is_from_gtfs'], unique=False)
    op.create_index(op.f('ix_route_stop_order'), 'route_stop', ['order'], unique=False)
    op.create_index(op.f('ix_route_stop_route_id'), 'route_stop', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stop_stop_id'), 'route_stop', ['stop_id'], unique=False)
    op.create_index(op.f('ix_siri_snapshot_etl_start_time'), 'siri_snapshot', ['etl_start_time'], unique=False)
    op.create_index(op.f('ix_siri_snapshot_snapshot_id'), 'siri_snapshot', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_stop_code'), 'stop', ['code'], unique=False)
    op.create_index(op.f('ix_stop_is_from_gtfs'), 'stop', ['is_from_gtfs'], unique=False)
    op.create_index(op.f('ix_stop_max_date'), 'stop', ['max_date'], unique=False)
    op.create_index(op.f('ix_stop_min_date'), 'stop', ['min_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_min_date'), table_name='stop')
    op.drop_index(op.f('ix_stop_max_date'), table_name='stop')
    op.drop_index(op.f('ix_stop_is_from_gtfs'), table_name='stop')
    op.drop_index(op.f('ix_stop_code'), table_name='stop')
    op.drop_index(op.f('ix_siri_snapshot_snapshot_id'), table_name='siri_snapshot')
    op.drop_index(op.f('ix_siri_snapshot_etl_start_time'), table_name='siri_snapshot')
    op.drop_index(op.f('ix_route_stop_stop_id'), table_name='route_stop')
    op.drop_index(op.f('ix_route_stop_route_id'), table_name='route_stop')
    op.drop_index(op.f('ix_route_stop_order'), table_name='route_stop')
    op.drop_index(op.f('ix_route_stop_is_from_gtfs'), table_name='route_stop')
    op.drop_index(op.f('ix_route_operator_ref'), table_name='route')
    op.drop_index(op.f('ix_route_min_date'), table_name='route')
    op.drop_index(op.f('ix_route_max_date'), table_name='route')
    op.drop_index(op.f('ix_route_line_ref'), table_name='route')
    op.drop_index(op.f('ix_route_is_from_gtfs'), table_name='route')
    op.drop_index(op.f('ix_ride_vehicle_ref'), table_name='ride')
    op.drop_index(op.f('ix_ride_scheduled_start_time'), table_name='ride')
    op.drop_index(op.f('ix_ride_route_id'), table_name='ride')
    op.drop_index(op.f('ix_ride_journey_ref'), table_name='ride')
    op.drop_index(op.f('ix_ride_is_from_gtfs'), table_name='ride')
    # ### end Alembic commands ###
