"""add gtfs_data_task table

Revision ID: a2518a3f5578
Revises: b7b60f01f422
Create Date: 2022-07-12 05:51:04.322680+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'a2518a3f5578'
down_revision = 'b7b60f01f422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtfs_data_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtfs_data_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('started_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True),
    sa.Column('completed_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['gtfs_data_id'], ['gtfs_data.id'], name=op.f('fk_gtfs_data_task_gtfs_data_id_gtfs_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gtfs_data_task'))
    )
    op.create_index('idx_gtfs_data_task_id_name', 'gtfs_data_task', ['gtfs_data_id', 'task_name'], unique=True)
    op.create_index(op.f('ix_gtfs_data_task_task_name'), 'gtfs_data_task', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gtfs_data_task_task_name'), table_name='gtfs_data_task')
    op.drop_index('idx_gtfs_data_task_id_name', table_name='gtfs_data_task')
    op.drop_table('gtfs_data_task')
    # ### end Alembic commands ###
