"""add ride, route_stop, vehicle_location tables

Revision ID: a39d8d6dcc87
Revises: 8e3e34ffec7c
Create Date: 2021-05-05 19:06:05.156726+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39d8d6dcc87'
down_revision = '8e3e34ffec7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siri_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('route_stop_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at_time', sa.DateTime(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('distance_from_journey_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stop.id'], ),
    sa.ForeignKeyConstraint(['siri_snapshot_id'], ['siri_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_location')
    op.drop_table('route_stop')
    op.drop_table('ride')
    # ### end Alembic commands ###
