"""add siri_vehicle_location.distance_from_siri_ride_stop_meters

Revision ID: abd8075c2d94
Revises: 731ae8564f97
Create Date: 2022-01-25 12:03:36.180376+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'abd8075c2d94'
down_revision = '731ae8564f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_vehicle_location', sa.Column('distance_from_siri_ride_stop_meters', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_vehicle_location', 'distance_from_siri_ride_stop_meters')
    # ### end Alembic commands ###
