"""add ride_stop table

Revision ID: af99c5a4971a
Revises: 9d73ef9c7fcc
Create Date: 2021-10-17 13:09:34.202677+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af99c5a4971a'
down_revision = '9d73ef9c7fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_stop_id', sa.Integer(), nullable=True),
    sa.Column('is_from_gtfs', sa.Boolean(), nullable=True),
    sa.Column('gtfs_arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('gtfs_departure_datetime', sa.DateTime(), nullable=True),
    sa.Column('gtfs_stop_sequence', sa.Integer(), nullable=True),
    sa.Column('gtfs_pickup_type', sa.Integer(), nullable=True),
    sa.Column('gtfs_drop_off_type', sa.Integer(), nullable=True),
    sa.Column('gtfs_shape_dist_traveled', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_stop_is_from_gtfs'), 'ride_stop', ['is_from_gtfs'], unique=False)
    op.create_index(op.f('ix_ride_stop_route_stop_id'), 'ride_stop', ['route_stop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_stop_route_stop_id'), table_name='ride_stop')
    op.drop_index(op.f('ix_ride_stop_is_from_gtfs'), table_name='ride_stop')
    op.drop_table('ride_stop')
    # ### end Alembic commands ###
