"""add artifact table

Revision ID: b40098600646
Revises: b3cb68e58942
Create Date: 2022-06-29 17:36:30.127306+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'b40098600646'
down_revision = 'b3cb68e58942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_prefix', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploading', 'error', 'success', name='artifactstatusenum'), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact'))
    )
    op.create_index(op.f('ix_artifact_created_at'), 'artifact', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifact_file_prefix'), 'artifact', ['file_prefix'], unique=False)
    op.create_index(op.f('ix_artifact_status'), 'artifact', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_status'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_file_prefix'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_created_at'), table_name='artifact')
    op.drop_table('artifact')
    # ### end Alembic commands ###
