"""change to gtfs_data table

Revision ID: b7b60f01f422
Revises: fa81f55b30ab
Create Date: 2022-07-10 10:32:11.970618+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'b7b60f01f422'
down_revision = 'fa81f55b30ab'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("truncate gtfs_data")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_data', sa.Column('download_upload_started_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True))
    op.add_column('gtfs_data', sa.Column('download_upload_completed_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True))
    op.add_column('gtfs_data', sa.Column('download_upload_error', sa.String(), nullable=True))
    op.add_column('gtfs_data', sa.Column('download_upload_success', sa.Boolean(), nullable=True))
    op.drop_index('ix_gtfs_data_date', table_name='gtfs_data')
    op.create_index(op.f('ix_gtfs_data_date'), 'gtfs_data', ['date'], unique=True)
    op.create_index(op.f('ix_gtfs_data_download_upload_started_at'), 'gtfs_data', ['download_upload_started_at'], unique=False)
    op.drop_column('gtfs_data', 'upload_success')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_data', sa.Column('upload_success', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_gtfs_data_download_upload_started_at'), table_name='gtfs_data')
    op.drop_index(op.f('ix_gtfs_data_date'), table_name='gtfs_data')
    op.create_index('ix_gtfs_data_date', 'gtfs_data', ['date'], unique=False)
    op.drop_column('gtfs_data', 'download_upload_success')
    op.drop_column('gtfs_data', 'download_upload_error')
    op.drop_column('gtfs_data', 'download_upload_completed_at')
    op.drop_column('gtfs_data', 'download_upload_started_at')
    # ### end Alembic commands ###
