"""remove gtfs_route_stop table

Revision ID: b85dbcc5226d
Revises: 9cc60dd15071
Create Date: 2022-01-17 10:04:57.391055+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'b85dbcc5226d'
down_revision = '9cc60dd15071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gtfs_route_stop_gtfs_route_id', table_name='gtfs_route_stop')
    op.drop_index('ix_gtfs_route_stop_gtfs_stop_id', table_name='gtfs_route_stop')
    op.drop_index('ix_gtfs_route_stop_order', table_name='gtfs_route_stop')
    op.drop_table('gtfs_route_stop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtfs_route_stop',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gtfs_stop_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gtfs_route_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gtfs_route_id'], ['gtfs_route.id'], name='fk_gtfs_route_stop_gtfs_route_id_gtfs_route'),
    sa.ForeignKeyConstraint(['gtfs_stop_id'], ['gtfs_stop.id'], name='fk_gtfs_route_stop_gtfs_stop_id_gtfs_stop'),
    sa.PrimaryKeyConstraint('id', name='pk_gtfs_route_stop')
    )
    op.create_index('ix_gtfs_route_stop_order', 'gtfs_route_stop', ['order'], unique=False)
    op.create_index('ix_gtfs_route_stop_gtfs_stop_id', 'gtfs_route_stop', ['gtfs_stop_id'], unique=False)
    op.create_index('ix_gtfs_route_stop_gtfs_route_id', 'gtfs_route_stop', ['gtfs_route_id'], unique=False)
    # ### end Alembic commands ###
