"""add-indicies-for-gtfs-ride-stop-start-time-arrival-time

Revision ID: c0fa93cfbf95
Revises: 4cdcf21fa073
Create Date: 2022-06-12 11:03:11.712535+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'c0fa93cfbf95'
down_revision = '4cdcf21fa073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gtfs_ride_start_time'), 'gtfs_ride', ['start_time'], unique=False)
    op.create_index(op.f('ix_gtfs_ride_stop_arrival_time'), 'gtfs_ride_stop', ['arrival_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gtfs_ride_stop_arrival_time'), table_name='gtfs_ride_stop')
    op.drop_index(op.f('ix_gtfs_ride_start_time'), table_name='gtfs_ride')
    # ### end Alembic commands ###
