"""add-index-for-siri-vehicle-location-lon-lat

Revision ID: cb63a0bc2879
Revises: 6c02b4e9bdad
Create Date: 2022-04-04 11:52:42.699762+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'cb63a0bc2879'
down_revision = '6c02b4e9bdad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_siri_vehicle_location_lat'), 'siri_vehicle_location', ['lat'], unique=False)
    op.create_index(op.f('ix_siri_vehicle_location_lon'), 'siri_vehicle_location', ['lon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siri_vehicle_location_lon'), table_name='siri_vehicle_location')
    op.drop_index(op.f('ix_siri_vehicle_location_lat'), table_name='siri_vehicle_location')
    # ### end Alembic commands ###
