"""add siri_route.gtfs_route_id

Revision ID: ccd51b939990
Revises: 10d0aa14d96b
Create Date: 2022-02-01 12:54:48.131799+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'ccd51b939990'
down_revision = '10d0aa14d96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('siri_route', sa.Column('gtfs_route_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siri_route', 'gtfs_route_id')
    # ### end Alembic commands ###
