"""add gtfs_ride first/last stop and times

Revision ID: da5d8fa25139
Revises: dfb819d34caa
Create Date: 2022-01-17 15:35:43.138859+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'da5d8fa25139'
down_revision = 'dfb819d34caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_ride', sa.Column('first_gtfs_ride_stop_id', sa.Integer(), nullable=True))
    op.add_column('gtfs_ride', sa.Column('last_gtfs_ride_stop_id', sa.Integer(), nullable=True))
    op.add_column('gtfs_ride', sa.Column('start_time', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True))
    op.add_column('gtfs_ride', sa.Column('end_time', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gtfs_ride', 'end_time')
    op.drop_column('gtfs_ride', 'start_time')
    op.drop_column('gtfs_ride', 'last_gtfs_ride_stop_id')
    op.drop_column('gtfs_ride', 'first_gtfs_ride_stop_id')
    # ### end Alembic commands ###
