"""remove gtfs_route scheduled_start_time and vehicle_ref

Revision ID: dfb819d34caa
Revises: b85dbcc5226d
Create Date: 2022-01-17 10:16:18.842154+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'dfb819d34caa'
down_revision = 'b85dbcc5226d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gtfs_ride_scheduled_start_time', table_name='gtfs_ride')
    op.drop_index('ix_gtfs_ride_vehicle_ref', table_name='gtfs_ride')
    op.drop_column('gtfs_ride', 'scheduled_start_time')
    op.drop_column('gtfs_ride', 'vehicle_ref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtfs_ride', sa.Column('vehicle_ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gtfs_ride', sa.Column('scheduled_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_gtfs_ride_vehicle_ref', 'gtfs_ride', ['vehicle_ref'], unique=False)
    op.create_index('ix_gtfs_ride_scheduled_start_time', 'gtfs_ride', ['scheduled_start_time'], unique=False)
    # ### end Alembic commands ###
