"""add gtfs_data table

Revision ID: fa81f55b30ab
Revises: 5b7ef0b1e875
Create Date: 2022-07-05 14:10:00.404167+00:00

"""
from alembic import op
import sqlalchemy as sa


import open_bus_stride_db


# revision identifiers, used by Alembic.
revision = 'fa81f55b30ab'
down_revision = '5b7ef0b1e875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtfs_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('processing_started_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True),
    sa.Column('processing_completed_at', open_bus_stride_db.model.base.DateTimeWithTimeZone(), nullable=True),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('processing_success', sa.Boolean(), nullable=True),
    sa.Column('upload_success', sa.Boolean(), nullable=True),
    sa.Column('processing_used_stride_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gtfs_data'))
    )
    op.create_index(op.f('ix_gtfs_data_date'), 'gtfs_data', ['date'], unique=False)
    op.create_index(op.f('ix_gtfs_data_processing_started_at'), 'gtfs_data', ['processing_started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gtfs_data_processing_started_at'), table_name='gtfs_data')
    op.drop_index(op.f('ix_gtfs_data_date'), table_name='gtfs_data')
    op.drop_table('gtfs_data')
    # ### end Alembic commands ###
